### ISSUE TITLE
Browse User currently has null pointer exception causing an activity crash if no offline file

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#180]
Steps:

Delete all offline users and the save files
Run the Browse User Activity Tests 
Observe crash of tests.

Expected: 

Tests fail due to "Fail" statement in test

Actual:

Tests fail due to "Null pointer exception" due to         ' return this.provider.getPatients(); ' line in Browse User Activity Controller in getPatientListOfProvider.

Error:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.cmput301f18t20.medicalphotorecord.Provider.getPatients()' on a null object reference
at Controllers.BrowseUserController.getPatientListOfProvider(BrowseUserController.java:91)
at Activities.BrowseUserActivity.onStart(BrowseUserActivity.java:48)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:686)
at android.app.Activity.performStart(Activity.java:7157)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Test running failed: Instrumentation run failed due to 'Process crashed.'

**Comment by tnguyen10** [comment]
This is because browse user controller return online the offline database. I'll change it so that it returns the elastic search results, but I think it'll only return 10 of them

**Comment by tnguyen10** [comment]
should be resolved with the recent pull request that only uses elastic search online database
